---

- name: waiting for ssh
  local_action:
    module: wait_for
    host: host="{{ ansible_ssh_host }}"
    port: 22
    search_regex: OpenSSH
    delay: 10
    timeout: 600
  sudo: no

- name: create path
  file:
    path: /etc/tmp
    state: directory
    mode: 0755

- name: show the message
  template:
    src: foo.conf.j2
    dest: /etc/tmp/foo.conf
    mode: 0755