---

- name: waiting for ssh
  local_action: wait_for port=22 host="{{ ansible_ssh_host }}" search_regex=OpenSSH delay=10

- name: create path
  file:
    path: /etc/tmp
    state: directory
    mode: 0755

- name: show the message
  template:
    src: foo.conf.j2
    dest: /etc/tmp/foo.conf
    mode: 0755